image: "node:12"

before_script:
  - npm install

pages:
  stage: deploy
#  environment:
#    name: production
#    url: https://kh2fm-rando-reports.com
  script:
    - npx eleventy --output=public --pathprefix=kh2fm-rando-reports
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  only:
    - master